Add persist configuration for store
saigon-technology/rn-base-project pull request #4
Opened 2022-11-06 16:38 UTC by loc-nguyenthien

2022-11-10 02:49 UTC, honghoangsts commented
We need add `REHYDRATE` for reducer.

2022-11-10 02:49 UTC, honghoangsts requested changes

2022-11-10 03:36 UTC, vunguyendhSTS approved these changes

2022-11-10 03:42 UTC, loido commented
Is it merge into branch master?

2022-11-15 03:29 UTC, loido approved these changes

2022-11-15 03:41 UTC, baonguyenhsts commented on template/src/store/reducers/index.js
> +  user: persistReducer(userPersistConfig, user),
I think he wants to use Nested Persists
https://github.com/rt2zz/redux-persist#nested-persists

2022-11-16 06:39 UTC, vunguyendhSTS commented on template/src/store/store.js
>  export {store}
seem it changed, please check it in latest commit @honghoangsts

2022-11-22 04:23 UTC, honghoangsts approved these changes

2022-11-22 04:23 UTC, merged